### PR TITLE
fix(sqlite): handle duplicate labels in an app manifest

### LINKED ISSUE #120: Spin app fails to deploy when two components reference NoOps DB with same label
Works fine locally with `spin up` but the deploy to cloud fails (see below)

```bash
mackenzieolson@MacKenzies-MacBook-Air spin-todo % spin cloud deploy --variable sqlite_username="REMOVED" --variable sqlite_password="REMOVED"
Warning: You're using a pre-release version of Spin (1.6.0-pre0). This plugin might not be compatible (supported: >=1.3). Continuing anyway.
Checking status (https://cloud.fermyon.com/)

Uploading todo-v2 version 0.1.0-r88287985 to Fermyon Cloud...
Deploying...
App "todo-v2" accesses a database labeled "default"
Would you like to link an existing database or create a new database?: Use an existing database and link app to it
Which database would you like to link to todo-v2 using the label "default": amiable-kiwi
App "todo-v2" accesses a database labeled "default"
Would you like to link an existing database or create a new database?: Use an existing database and link app to it
Which database would you like to link to todo-v2 using the label "default": amiable-kiwi
Error: Failed to link database "amiable-kiwi" to app "todo-v2"

Caused by:
    This database and app have already been linked with this label.

Learn more at https://developer.fermyon.com/cloud/faq
```

```toml
[[component]]
id = "todo-api"
source = "target/wasm32-wasi/release/todo.wasm"
allowed_http_hosts = []
sqlite_databases = ["default"]
[component.trigger]
route = "/api/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*", "Cargo.toml"]

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "fileserver"
files = [{ source = "static", destination = "/" }]
[component.trigger]
route = "/..."

[variables]
sqlite_username = { required = true }
sqlite_password = { required = true }

[[component]]
id = "sql-cli"
source = { url = "https://github.com/karthik2804/spin-sqlite-web-cli/releases/download/v0.0.1/spin-sqlite-web-cli.wasm", digest = "sha256:e0fb024ffaa68e53118a6b45636161d2a43543cf2bd0b6d027d01a34f4ee56e4" }
sqlite_databases = ["default"]
[component.trigger]
route = "/internal/sqlite/..."
[component.config]
sqlite_username = { required = true }
sqlite_password = { required = true }
```

### PR DESCRIPTION
**Pull request by kate-goldenring**
fixes #120

### CODE REVIEW

File: src/commands/deploy.rs [hunk 1]
```diff
@@ -233,7 +233,7 @@ impl DeployCommand {
         // Create or update app
         let channel_id = match get_app_id_cloud(&client, &name).await? {
             Some(app_id) => {
-                let labels = application.sqlite_databases();
+                let labels: HashSet<String> = application.sqlite_databases();
```
Comment (itowlson) [inline src/commands/deploy.rs:236]: nit: this seems like it would not be needed?

**Review by itowlson — APPROVED** [review]
Mea culpa, thanks for the fix!

**Review by vdice — APPROVED** [review]

**Review by karthik2804 — APPROVED** [review]
